<?xml version="1.0"?>
<package format="2">
  <name>spraying_car_description</name>
  <version>0.0.1</version>
  <description>URDF and robot description package for the spraying car.</description>

  <maintainer email="dev@example.com">Spraying Car Project</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>rviz</exec_depend>
  <exec_depend>xacro</exec_depend>
</package>
