TebLocalPlannerROS:
  odom_topic: /odom
  map_frame: map

  max_vel_x: 0.6
  max_vel_x_backwards: 0.2
  max_vel_theta: 0.8
  acc_lim_x: 0.3
  acc_lim_theta: 0.5

  min_turning_radius: 1.0
  wheelbase: 0.82
  cmd_angle_instead_rotvel: false

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.15
