#!/usr/bin/env python3
"""Convert an ASCII PCD point cloud into a simple 2D occupancy grid map."""

import argparse
import datetime as _dt
import math
from pathlib import Path
import re
import sys


PROJECT_ROOT = Path(__file__).resolve().parents[5]
MAP_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")


def ros_args_to_cli(argv):
    converted = []
    for item in argv:
        if item.startswith("__"):
            continue
        if ":=" in item:
            key, value = item.split(":=", 1)
            key = key.lstrip("_").replace("_", "-")
            if key:
                converted.extend(["--" + key, value])
            continue
        converted.append(item)
    return converted


def resolve_path(value, default_base=PROJECT_ROOT):
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = default_base / path
    return path.resolve()


def validate_map_name(map_name):
    if not map_name or not MAP_NAME_RE.match(map_name):
        raise ValueError("output_name must match [A-Za-z0-9][A-Za-z0-9_.-]*")
    return map_name


def parse_pcd_ascii(path):
    fields = None
    data_mode = None
    data_start = None
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()

    for index, raw in enumerate(lines):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        key = parts[0].upper()
        if key == "FIELDS":
            fields = parts[1:]
        elif key == "DATA":
            if len(parts) < 2:
                raise ValueError("PCD DATA header is missing a mode")
            data_mode = parts[1].lower()
            data_start = index + 1
            break

    if fields is None:
        raise ValueError("PCD header does not contain FIELDS")
    if data_mode is None or data_start is None:
        raise ValueError("PCD header does not contain DATA")
    if data_mode != "ascii":
        raise ValueError(f"Only ASCII PCD is supported by this first-stage tool; got DATA {data_mode}")

    try:
        x_i = fields.index("x")
        y_i = fields.index("y")
        z_i = fields.index("z")
    except ValueError as exc:
        raise ValueError("PCD FIELDS must contain x y z") from exc

    points = []
    for line_no, raw in enumerate(lines[data_start:], start=data_start + 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) <= max(x_i, y_i, z_i):
            raise ValueError(f"PCD data line {line_no} has too few fields")
        try:
            x = float(parts[x_i])
            y = float(parts[y_i])
            z = float(parts[z_i])
        except ValueError as exc:
            raise ValueError(f"PCD data line {line_no} contains non-numeric xyz") from exc
        if math.isfinite(x) and math.isfinite(y) and math.isfinite(z):
            points.append((x, y, z))
    return points


def inflate_cells(occupied, width, height, radius_cells):
    if radius_cells <= 0:
        return set(occupied)
    inflated = set()
    radius_sq = radius_cells * radius_cells
    offsets = []
    for dy in range(-radius_cells, radius_cells + 1):
        for dx in range(-radius_cells, radius_cells + 1):
            if dx * dx + dy * dy <= radius_sq:
                offsets.append((dx, dy))
    for col, row in occupied:
        for dx, dy in offsets:
            new_col = col + dx
            new_row = row + dy
            if 0 <= new_col < width and 0 <= new_row < height:
                inflated.add((new_col, new_row))
    return inflated


def write_pgm(path, grid, occupied_value, free_value, unknown_value):
    height = len(grid)
    width = len(grid[0]) if height else 0
    with path.open("wb") as handle:
        handle.write(f"P5\n# generated by pcd_to_occupancy_grid.py\n{width} {height}\n255\n".encode("ascii"))
        for row in reversed(grid):
            handle.write(bytes(max(0, min(255, int(value))) for value in row))


def write_map_yaml(path, image_name, resolution, origin_x, origin_y):
    text = "\n".join(
        [
            f"image: {image_name}",
            f"resolution: {resolution:.6f}",
            f"origin: [{origin_x:.6f}, {origin_y:.6f}, 0.0]",
            "negate: 0",
            "occupied_thresh: 0.65",
            "free_thresh: 0.196",
            "",
        ]
    )
    path.write_text(text, encoding="utf-8")


def quote_yaml(value):
    text = "" if value is None else str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_grid_metadata(path, args, input_pcd, pgm_path, yaml_path, origin, width, height, point_count, obstacle_count):
    lines = [
        f"map_name: {quote_yaml(args.output_name)}",
        f"created_at: {quote_yaml(_dt.datetime.now().isoformat(timespec='seconds'))}",
        f"source_pcd: {quote_yaml(input_pcd)}",
        f"pgm_path: {quote_yaml(pgm_path)}",
        f"yaml_path: {quote_yaml(yaml_path)}",
        f"resolution: {args.resolution}",
        f"origin: [{origin[0]:.6f}, {origin[1]:.6f}, 0.0]",
        f"height_filter_min: {args.height_min}",
        f"height_filter_max: {args.height_max}",
        f"inflation_radius: {args.inflation_radius}",
        f"width: {width}",
        f"height: {height}",
        f"filtered_point_count: {point_count}",
        f"occupied_cell_count: {obstacle_count}",
        "notes: \"Generated from ASCII PCD by a first-stage projection tool; verify before navigation.\"",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def convert(args):
    output_name = validate_map_name(args.output_name)
    input_pcd = resolve_path(args.input_pcd)
    output_dir = resolve_path(args.output_dir)
    metadata_dir = resolve_path(args.metadata_dir)

    if not input_pcd.exists():
        raise FileNotFoundError(f"input_pcd does not exist: {input_pcd}")
    if args.resolution <= 0:
        raise ValueError("resolution must be > 0")
    if args.height_min > args.height_max:
        raise ValueError("height_min must be <= height_max")
    if args.inflation_radius < 0:
        raise ValueError("inflation_radius must be >= 0")

    all_points = parse_pcd_ascii(input_pcd)
    filtered = [(x, y, z) for x, y, z in all_points if args.height_min <= z <= args.height_max]
    if not filtered:
        raise ValueError("No points remain after height filtering")

    xs = [p[0] for p in filtered]
    ys = [p[1] for p in filtered]
    margin = max(args.inflation_radius + args.resolution, args.resolution)
    interior_min_x = min(xs)
    interior_max_x = max(xs)
    interior_min_y = min(ys)
    interior_max_y = max(ys)
    origin_x = interior_min_x - margin
    origin_y = interior_min_y - margin
    max_x = interior_max_x + margin
    max_y = interior_max_y + margin
    width = max(1, int(math.ceil((max_x - origin_x) / args.resolution)) + 1)
    height = max(1, int(math.ceil((max_y - origin_y) / args.resolution)) + 1)

    grid = [[args.unknown_value for _ in range(width)] for _ in range(height)]

    min_col = max(0, int(math.floor((interior_min_x - origin_x) / args.resolution)))
    max_col = min(width - 1, int(math.ceil((interior_max_x - origin_x) / args.resolution)))
    min_row = max(0, int(math.floor((interior_min_y - origin_y) / args.resolution)))
    max_row = min(height - 1, int(math.ceil((interior_max_y - origin_y) / args.resolution)))
    for row in range(min_row, max_row + 1):
        for col in range(min_col, max_col + 1):
            grid[row][col] = args.free_value

    occupied = set()
    for x, y, _ in filtered:
        col = int(math.floor((x - origin_x) / args.resolution))
        row = int(math.floor((y - origin_y) / args.resolution))
        if 0 <= col < width and 0 <= row < height:
            occupied.add((col, row))

    inflated = inflate_cells(occupied, width, height, int(math.ceil(args.inflation_radius / args.resolution)))
    for col, row in inflated:
        grid[row][col] = args.occupied_value

    output_dir.mkdir(parents=True, exist_ok=True)
    metadata_dir.mkdir(parents=True, exist_ok=True)
    pgm_path = output_dir / f"{output_name}.pgm"
    yaml_path = output_dir / f"{output_name}.yaml"
    meta_path = metadata_dir / f"{output_name}_grid.meta.yaml"

    write_pgm(pgm_path, grid, args.occupied_value, args.free_value, args.unknown_value)
    write_map_yaml(yaml_path, pgm_path.name, args.resolution, origin_x, origin_y)
    write_grid_metadata(meta_path, args, input_pcd, pgm_path, yaml_path, (origin_x, origin_y), width, height, len(filtered), len(inflated))
    return pgm_path, yaml_path, meta_path


def parse_args(argv):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input-pcd", required=True)
    parser.add_argument("--output-name", required=True)
    parser.add_argument("--output-dir", default=str(PROJECT_ROOT / "maps/grid"))
    parser.add_argument("--metadata-dir", default=str(PROJECT_ROOT / "maps/metadata"))
    parser.add_argument("--resolution", type=float, default=0.10)
    parser.add_argument("--height-min", type=float, default=0.15)
    parser.add_argument("--height-max", type=float, default=1.5)
    parser.add_argument("--inflation-radius", type=float, default=0.30)
    parser.add_argument("--unknown-value", type=int, default=205)
    parser.add_argument("--occupied-value", type=int, default=0)
    parser.add_argument("--free-value", type=int, default=254)
    return parser.parse_args(ros_args_to_cli(argv))


def main(argv=None):
    args = parse_args(sys.argv[1:] if argv is None else argv)
    try:
        pgm_path, yaml_path, meta_path = convert(args)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"Wrote PGM: {pgm_path}")
    print(f"Wrote YAML: {yaml_path}")
    print(f"Wrote metadata: {meta_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
